pipeline {
  agent { docker { image 'python:3.7.2' } }
  environment {
    CONSUMER_KEY = 'R84A3vsG8fMMAO4btiEehPWQD'
    CONSUMER_SECRET = 'ihfi2Axa00tLB7S7mrZ3DBKWg3XwP6me5kBHU4WO2hLgJHnM42'
    ACCESS_TOKEN= '1309472982234849280-IAjX1txVzaNEq5mdXXPrYmg7gxAszm'
    ACCESS_TOKEN_SECRET='DMoAX5ou8eOhKyjSpeaMrAvxIbJvBGz1jYJvxx4631LBx'
  }
  stages {
    stage('build') {
      steps {
        sh 'pip install -r requirements.txt'
        sh 'python flask_app.py &'
      }
    }
  }
}
