# serverless.yml

service: marsnest-user-application-api

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    USERS_TABLE: 'users'
    USERS_APPLICATION_TABLE: 'user_applications'
  

functions:
  main:
    handler: app.main
    events:
      - http: 'GET /'
  showAllApplications:
    handler: app.showAllApplications
    events:
      - http: 'GET /user_applications'
  showUserApplications:
    handler: app.showUserApplications
    events:
      - http: 'GET /user/user_applications'
  createUserApplication:
    handler: app.createUserApplication
    events:
      - http: 'GET /user_application/create'
  getUserApplication:
    handler: app.getUserApplication
    events:
      - http: 'GET /user_application'
  createUser:
    handler: app.createUser
    events:
      - http: 'GET /users'
  # getUserById:
  #   handler: app.getUserById
  #   events:
  #     - http: 'GET /users/id'
  getUserByEmail:
    handler: app.getUserByEmail
    events:
      - http: 'GET /users/email'
  updateUser:
    handler: app.updateUser
    events:
      - http: 'GET /users/update'
  